/**
 * @file    ml_model.h
 * @brief   AUTO-GENERATED by train_model.py — do not hand-edit.
 */

#ifndef ML_MODEL_H
#define ML_MODEL_H

#define ML_NUM_CLASSES  3

extern const char * const ML_CLASS_LABELS[ML_NUM_CLASSES];

/* Returns the predicted class index (0/1/2) — look up
 * ML_CLASS_LABELS[result] for the string name. */
int ml_predict_class(float co2_aoutv, float alc_aoutv);

#endif /* ML_MODEL_H */
