/**
 * @file    ml_model.c
 * @brief   AUTO-GENERATED by train_model.py — do not hand-edit.
 *          RandomForest (25 trees, max_depth=5)
 *          compiled directly into C via m2cgen. No runtime needed.
 *
 * Class order (index 0/1/2): ['openair', 'regular', 'activatedcharcoal']
 */

#include "ml_model.h"
#include <string.h>

#include <string.h>
void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static void ml_score(double * input, double * output) {
    double var0[3];
    double var1[3];
    double var2[3];
    double var3[3];
    double var4[3];
    double var5[3];
    double var6[3];
    double var7[3];
    double var8[3];
    double var9[3];
    double var10[3];
    double var11[3];
    double var12[3];
    double var13[3];
    double var14[3];
    double var15[3];
    double var16[3];
    double var17[3];
    double var18[3];
    double var19[3];
    double var20[3];
    double var21[3];
    double var22[3];
    double var23[3];
    double var24[3];
    double var25[3];
    if (input[0] <= 1.0719999969005585) {
        memcpy(var25, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.833000063896179) {
            memcpy(var25, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var25, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    }
    double var26[3];
    if (input[2] <= 2.201016068458557) {
        if (input[2] <= 1.4530285000801086) {
            memcpy(var26, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var26, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var26, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var25, var26, 3, var24);
    double var27[3];
    if (input[1] <= 2.1834999918937683) {
        memcpy(var27, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.833000063896179) {
            memcpy(var27, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var27, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var24, var27, 3, var23);
    double var28[3];
    if (input[2] <= 1.4524483680725098) {
        memcpy(var28, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.1800000071525574) {
            memcpy(var28, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var28, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var23, var28, 3, var22);
    double var29[3];
    if (input[2] <= 1.4572508335113525) {
        memcpy(var29, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.1834999918937683) {
            memcpy(var29, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var29, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var22, var29, 3, var21);
    double var30[3];
    if (input[1] <= 2.833000063896179) {
        if (input[1] <= 2.1834999918937683) {
            memcpy(var30, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var21, var30, 3, var20);
    double var31[3];
    if (input[1] <= 2.833000063896179) {
        if (input[2] <= 2.1993157267570496) {
            memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var31, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var20, var31, 3, var19);
    double var32[3];
    if (input[0] <= 1.981000006198883) {
        if (input[1] <= 2.18450003862381) {
            memcpy(var32, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var19, var32, 3, var18);
    double var33[3];
    if (input[2] <= 2.1994439363479614) {
        if (input[1] <= 2.8320000171661377) {
            memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var33, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var18, var33, 3, var17);
    double var34[3];
    if (input[0] <= 1.981000006198883) {
        if (input[1] <= 2.178999960422516) {
            memcpy(var34, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var34, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var17, var34, 3, var16);
    double var35[3];
    if (input[0] <= 1.981000006198883) {
        if (input[2] <= 2.1994439363479614) {
            memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var35, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var16, var35, 3, var15);
    double var36[3];
    if (input[2] <= 1.4530285000801086) {
        memcpy(var36, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.1834999918937683) {
            memcpy(var36, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var15, var36, 3, var14);
    double var37[3];
    if (input[2] <= 1.4582868814468384) {
        memcpy(var37, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[0] <= 1.071999967098236) {
            memcpy(var37, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var14, var37, 3, var13);
    double var38[3];
    if (input[2] <= 2.2088595628738403) {
        if (input[0] <= 1.9820000529289246) {
            memcpy(var38, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var38, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var38, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var13, var38, 3, var12);
    double var39[3];
    if (input[1] <= 2.1834999918937683) {
        memcpy(var39, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 2.8320000171661377) {
            memcpy(var39, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var39, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var12, var39, 3, var11);
    double var40[3];
    if (input[1] <= 2.1834999918937683) {
        memcpy(var40, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 1.4584458470344543) {
            memcpy(var40, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var40, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var11, var40, 3, var10);
    double var41[3];
    if (input[0] <= 1.0694999992847443) {
        memcpy(var41, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 1.4584458470344543) {
            memcpy(var41, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var41, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var10, var41, 3, var9);
    double var42[3];
    if (input[0] <= 1.9815000295639038) {
        if (input[1] <= 2.18450003862381) {
            memcpy(var42, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var42, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var9, var42, 3, var8);
    double var43[3];
    if (input[1] <= 2.178999960422516) {
        memcpy(var43, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[0] <= 1.9815000295639038) {
            memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var43, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var8, var43, 3, var7);
    double var44[3];
    if (input[2] <= 1.4524483680725098) {
        memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 2.200695753097534) {
            memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var44, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var7, var44, 3, var6);
    double var45[3];
    if (input[1] <= 2.1764999628067017) {
        memcpy(var45, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 1.4530285000801086) {
            memcpy(var45, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var6, var45, 3, var5);
    double var46[3];
    if (input[0] <= 1.0694999992847443) {
        memcpy(var46, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[0] <= 1.983500063419342) {
            memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var46, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var5, var46, 3, var4);
    double var47[3];
    if (input[1] <= 2.8315000534057617) {
        if (input[2] <= 2.1994439363479614) {
            memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            memcpy(var47, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var47, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    }
    add_vectors(var4, var47, 3, var3);
    double var48[3];
    if (input[1] <= 2.185000002384186) {
        memcpy(var48, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 1.4530285000801086) {
            memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var3, var48, 3, var2);
    double var49[3];
    if (input[1] <= 2.1834999918937683) {
        memcpy(var49, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[2] <= 1.4519924521446228) {
            memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var2, var49, 3, var1);
    mul_vector_number(var1, 0.04, 3, var0);
    memcpy(output, var0, 3 * sizeof(double));
}


const char * const ML_CLASS_LABELS[ML_NUM_CLASSES] = { "openair", "regular", "activatedcharcoal" };

int ml_predict_class(float co2_aoutv, float alc_aoutv)
{
    double ratio = (co2_aoutv != 0.0f) ? (double)(alc_aoutv / co2_aoutv) : 0.0;
    double input[3]  = { (double)co2_aoutv, (double)alc_aoutv, ratio };
    double output[ML_NUM_CLASSES];

    ml_score(input, output);

    int best_idx = 0;
    for (int i = 1; i < ML_NUM_CLASSES; i++)
    {
        if (output[i] > output[best_idx])
        {
            best_idx = i;
        }
    }

    return best_idx;
}
